### PR TITLE
uart: implement embedded_serial::{NonBlockingTx, BlockingRx}

### PR DESCRIPTION
**Pull request by astraw**

### CODE REVIEW

**Review by thejpster — CHANGES_REQUESTED** [review]
Many thanks for this. It's so exciting to think someone else is finding this useful! One nit - can you fix the comment for the blocking getc to indicate that it can't actually fail?

**Review by thejpster — APPROVED** [review]

**Comment by thejpster** [comment]
Thank you!

**Comment by astraw** [comment]
Good point, I updated the docstring. Thanks to you.

**Comment by astraw** [comment]
By the way, here where I needed this https://github.com/astraw/framed-serial .

It would be great to get a new release for lm4f120 and also for you to publish launchpad-rs to crates.io.

**Comment by thejpster** [comment]
Lm4f120 has been updated but I can't publish launchpad-rs while it depends
on a git copy of compiler-builtins. Maybe the snapshot on crates.io is
sufficient but I'll need to check first.

**Pull request merged**
